      - pytorch_linux_build:
          name: pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_build
          build_environment: "pytorch-linux-xenial-py3-clang5-android-ndk-r19c-x86_32"
          requires:
            - setup
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:339"
      - pytorch_linux_build:
          name: pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_64_build
          build_environment: "pytorch-linux-xenial-py3-clang5-android-ndk-r19c-x86_64"
          requires:
            - setup
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:339"
      - pytorch_linux_build:
          name: pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v7a_build
          build_environment: "pytorch-linux-xenial-py3-clang5-android-ndk-r19c-arm-v7a"
          requires:
            - setup
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:339"
      - pytorch_linux_build:
          name: pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v8a_build
          build_environment: "pytorch-linux-xenial-py3-clang5-android-ndk-r19c-arm-v8a"
          requires:
            - setup
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:339"

      - pytorch_android_gradle_build:
          name: pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_android_gradle_build
          requires:
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_build
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_64_build
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v7a_build
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v8a_build

      - pytorch_android_publish_snapshot:
          name: pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_android_publish_snapshot
          requires:
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_android_gradle_build
          context: org-member
