      - pytorch_android_gradle_build-x86_32:
          name: pytorch-linux-xenial-py3-clang5-android-ndk-r19c-gradle-build-x86_32
          requires:
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_build

      - pytorch_android_gradle_build:
          name: pytorch-linux-xenial-py3-clang5-android-ndk-r19c-gradle-build
          requires:
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_build
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_64_build
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v7a_build
            - pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v8a_build

      - pytorch_android_publish_snapshot:
          name: pytorch-linux-xenial-py3-clang5-android-ndk-r19c-gradle-publish-snapshot
          requires:
            - pytorch-linux-xenial-py3-clang5-android-ndk-r19c-gradle-build-x86_32
            #- pytorch-linux-xenial-py3-clang5-android-ndk-r19c-gradle-build
          context: org-member

